# Specify the Docker Compose file format version
version: '3.8'

# Define the services that make up your app
services:
  # The name of the service
  app:
    # The name of the Docker image to use for this service
    image: portfolio-app

    # Settings for building the Docker image
    build:
      # The build context path
      context: ./

      # The target build stage to build
      target: dev

      # The name of the Dockerfile to use
      dockerfile: Dockerfile

    # Paths or named volumes to mount
    volumes:
        # Mount the current directory to the /app directory in the container
        - .:/app

        # Mount the /app/node_modules directory as a separate volume
        - /app/node_modules

        # Mount the /app/.next directory as a separate volume
        - /app/.next

    # Map the container's ports to the host's ports
    ports:
      # Map port 3000 of the container to port 3000 of the host
      - "3000:3000"